### PR TITLE
Only save user-assigned order addresses if they are not new records.

### PR DESCRIPTION
**Pull request by mike-bourgeous**
Also don't try to save invalid addresses and reenable merging.

### CODE REVIEW

**Comment by ericsaupe** [comment]
This looks good. I like the checks. In the heat of the moment I couldn't see the proper way to fix this but I like these. :panda_face:

**Comment by mike-bourgeous** [comment]
This PR is, in part, a workaround for https://github.com/spree/spree_auth_devise/issues/300

**Comment by ericsaupe** [comment]
Looks good :panda_face:

**Comment by mike-bourgeous** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nsUxQIMP&#x2F;3885-1-reevaluate-address-merge"> (1) Reevaluate address merge</a>

**Pull request merged**
