### PR TITLE
Global address management from the Spree admin UI

### PR DESCRIPTION
**Pull request by mike-bourgeous**
This pull request finishes and enhances the admin UI started by Alejandro, adds address deduplication features (with extensive testing thereof), and improves the UI for selecting and editing addresses on the user's My Account page.

### CODE REVIEW

**Comment by mike-bourgeous** [comment]
The verbose and colorful debugging output has finally paid off in the form of passing tests.

shot1

**Comment by mike-bourgeous** [comment]
Frontend address list in my account:

snapshot1

**Comment by mike-bourgeous** [comment]
Improvements to checkout address list:

shot1

**Comment by ericsaupe** [comment]
Looks good :panda_face:

**Pull request merged**
